### ISSUE TITLE
Heroku で css や js が読み込まれない

### ISSUE THREAD

**Issue by odaillyjp** [sanemat/gist-mail#225]
Rails 4 にアップデート後、ローカルの production 環境では css や js は読み込まれるのに、 heroku の production 環境だと css や js が読み込まれない。

![gistmail](https://cloud.githubusercontent.com/assets/1294999/2691785/95bdaef0-c38c-11e3-939a-b340c1a24100.jpg)

この症状と同じ？？？
http://stackoverflow.com/questions/16271696/cant-get-css-working-on-heroku-using-rails-4-with-bootstrap-saas-gem

**Comment by sanemat** [comment]
うまく動いてるようにみえる or 修正済みかな
![screen shot 2014-04-22 at 10 59 16](https://cloud.githubusercontent.com/assets/75448/2767715/0ebcb742-ca3b-11e3-9933-2d3ccb8f7765.png)

**Comment by odaillyjp** [comment]
まだ修正していません。見た目があのままだと良くないので、heroku rollback しました。

**Comment by odaillyjp** [comment]
Heroku で Rails4 アプリを動かすために
- rails_12factor を追加 #227
- Heroku で Rails4 を動かすために必要な実行ファイルを作成 #228

の二つの修正が必要でした。
（いろいろと試していましたので pull-req を二つに分けてしまいました。）
heroku にデプロイ済みですので、現在は Rails 4 で動いています。

# 参考

https://devcenter.heroku.com/articles/rails4

**Comment by sanemat** [comment]
:heart_eyes:
